# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - 'v*.*.*' # 仅在推送版本标签时触发

permissions:
  contents: read

jobs:
  release-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'
          
      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          pip install --upgrade pip
          pip install cn2an
          pip install pyinstaller
          pyinstaller -F -w main.py
          
      - name: Upload EXE to GitHub Packages
        run: |
          # 定义包的名称和版本
          PACKAGE_NAME="nian-str-count"
          VERSION="${GITHUB_REF#refs/tags/}"
          
          # 创建 GitHub Packages 的通用包
          gh package publish file \
            "dist/main.exe" \
            --repository "${{ github.repository }}" \
            --package-type generic \
            --package-name "$PACKAGE_NAME" \
            --package-version "$VERSION"
          
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
